service: sls-ts

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    packager: npm
#  custom:
#    stages:
#      dev:
#        domainEnabled: false
#      staging:
#        domain: staging.halfstack.software
#      prod:
#        domain: halfstack.software

provider:
  name: aws
  environment:
    MY_SECRET: tester
  region: us-east-2
  runtime: nodejs14.x
#  vpc:
#    securityGroupIds:
#      - sg-98f38XXX
#    subnetdIds:
#      - subnet-978ffXXX
#      - subnet-5e59fXXX

functions:
  myFunction:
    handler: src/myFunction.handler